name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/checkout@v4
        with:
          name: build app
          uses: actions/setup-node@v1
          node-version: 20.18.0
      - run: npm ci # npm installをciではこうやる
        env:
            CI: true # 現在の環境がci環境かどうか
          
  deploy:
    needs: build
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
      - uses: actions/checkout@4
      
        id: deployment