name: Deploy to Vercel

on:
  workflow_run:
    workflows: ['Build and Test'] # build.yml の `name` を指定
    types:
      - completed

jobs:
  deploy:
    # 'Build and Test' ワークフローが成功し、かつ main ブランチへの push がトリガーだった場合のみ実行
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # トリガーとなったワークフローのコミットをチェックアウト
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Deploy to Vercel Production
        uses: vercel/vercel-action@v3
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-prod: true # 本番環境へのデプロイ
